[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.0.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_SKIP_TYPE_CHECK = "true"
  NEXT_ESLINT_IGNORE_ERRORS = "true"
  CI = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"
